# Generated by Django 5.0.7 on 2024-07-20 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newprjct', '0002_prjvariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjvariety',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
